[project]
name = "neotest-bokehjs"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"] # , "win-64"]

[activation.env]
LAZY_STDPATH = ".pixi/lazy"

[tasks]
install = { cmd = 'nvim -l ./tests/busted.lua --version', env = { LAZY_INSTALL = "true" } }
test = 'nvim -l ./tests/busted.lua tests'

[dependencies]
nvim = "*"
nodejs = "*"
luarocks = "*"
