[project]
name = "neotest-bokehjs"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[activation.env]
LAZY_STDPATH = ".pixi/lazy"

[tasks]
install = 'nvim -l tests/busted.lua --install'
test = 'nvim -l tests/busted.lua tests/'

[dependencies]
nvim = "*"
nodejs = "*"
