[project]
name = "neotest-bokehjs"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"] # , "win-64"]

[tasks]
# install = ''
# test = ''

[dependencies]
nvim = "*"
nodejs = "*"
