name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: hoxbro/actions/pre-commit@main

  unit-test:
    name: unit:${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "1"
      - uses: prefix-dev/setup-pixi@v0.8.1
      - name: Install
        shell: bash -e {0}
        run: pixi run install
      - name: Test
        shell: bash -e {0}
        run: pixi run test
